bencher/src/lib.rs, bencher/tests/markdown.rs, harness/benches/ips.rs, harness/src/lib.rs, harness/tests/bpf_program.rs, harness/tests/system_program.rs
=> accounts: use slice instead of vec

harness/src/lib.rs, harness/src/program.rs, harness/tests/bpf_program.rs
Update the program API - methods like `system_program_account` to return
a `(Pubkey, AccountSharedData)` for use in test runs.
Renames the like to just `system_program()`.
=> Update program API

harness/src/lib.rs, harness/src/program.rs
Add some helpers and adjust the program cache API for working with raw ELFs.
cc @OliverNChalk
=> Program loader helpers

harness/src/program.rs, scripts/build-test-programs.sh
Add the BPF Loader 2 to the default program cache. This allows Mollusk
to support CPI to BPF Loader 2 programs.
cc @OliverNChalk
=> Add BPF Loader 2 to cache

harness/src/lib.rs, harness/src/program.rs, harness/src/sysvar.rs, harness/tests/bpf_program.rs
- Rename account helpers to use "keyed account" wording.
- Add new account helpers for sysvars.
=> Update account helpers

harness/src/result.rs, harness/tests/bpf_program.rs
- Reorder the account checks (actual/expected). This new order might look funky, but it works better with the syntax of check creation in unit tests.
- Add two new check types: `executable` and `space`.
=> Add new account checks

harness/src/lib.rs
- Adds more helpers for adding new programs to the cache.
- Adds new helpers for switching the target program on an existing Mollusk instance.
=> Add more program helpers

harness/src/lib.rs, harness/src/sysvar.rs
Adds a fix for updating the `SlotHashes` sysvar when warping to a slot.
Simply uses `SlotHashes::add` instead of overwriting the slice, allowing the binary search method to pop expired entries out.
The first commit has nothing to do with warping slots, but it managed to squeak in here, so it's hitching a ride.
=> Fix: slot hash warping

harness/src/lib.rs, harness/tests/bpf_program.rs, test-programs/primary/src/lib.rs
Currently, if you provide the same account twice to Mollusk's `process_instruction` API, the permissions are taken directly from the instruction `AccountMeta` entries, so even if two metas have the same public key, their perms as `AccountInfo` will reflect those of the instruction metas.
In other words, if I provide the same account twice, as so...
```rust
let key = Pubkey::new_unique();
let metas = vec![
AccountMeta::new(key, false),         // writable
AccountMeta::new_readonly(key, true), // signer
];
```
... then my program will see the first account as writable, and the second as a signer, but they will have the same address. These must be coalesced, as is done in the VM's serialization step. Unfortunately, this deduping depends on the `TransactionContext`, so this fix has to go into …
=> Harness: Dedupe accounts and coalesce privileges

harness/src/keys.rs, harness/src/lib.rs, harness/src/program.rs, harness/tests/bpf_program.rs
Currently, if the same account is used twice in an instruction, and twice in the accounts list, Mollusk will not unify the roles of the accounts. For example, consider the following instruction:
```
1. [ writable ] Account 1
2. [  signer  ] Account 2
```
If the same key was provided for both accounts 1 & 2, they would be serialized into the VM as separate accounts with the following roles:
```
{
account_1: { is_signer: false, is_writable: true }
account_2: { is_signer: true, is_writable: false }
}
```
Instead they should both be writable and both be signer.
Partially reimplement the transaction compilation used in [`Message::new_with_blockhash`](https://github.com/anza-xyz/agave/blob/c6e8239843af8e6301cd198e39d0a44add427bef/sdk/program/src/message/legacy.rs#L357) to build out the …
=> fix: transaction account dedupe and roles

harness/src/lib.rs, harness/src/program.rs, harness/tests/bpf_program.rs
Now that we're stubbing the program account in the transaction context - like the validator runtime does - we can remove the concept of "target programs" in Mollusk.
Drop the `program_id` and `program_account` fields from the `Mollusk` struct. Also eliminate now irrelevant API methods.
Now, as long as a program has been added to the cache, Mollusk can be used to target it. `Mollusk::new(program_id, program_name)` will still create a new instance with the provided program cached.
=> feat: remove program targeting

harness/src/lib.rs, harness/src/result.rs, harness/tests/instruction_chain.rs, harness/tests/system_program.rs
Currently, Mollusk only supports single instructions. However, there are many use cases where one may wish to test a few instructions consecutively. To do this right now, you'd have to manually take the accounts from the first instruction's result and pipe them into the next one, and so on.
Offer a new API (`process_instruction_chain`) for processing a chain of instructions. Thanks to #29, accounts can be provided in any order, so this implementation was trivial, and is easy to use.
Closes #26
=> feat: API for chaining of instructions

harness/src/fuzz/firedancer.rs, harness/src/fuzz/mod.rs, harness/src/fuzz/mollusk.rs, harness/src/lib.rs, harness/src/result.rs, harness/src/sysvar.rs, harness/tests/process_fixture.rs
This PR gives Mollusk the ability to process fuzz fixtures directly from a provided fixture.
Previously Mollusk could only generate fixtures, but now it can accept them and process them against its own harness.
Note: Requires either the `fuzz` or `fuzz-fd` feature.
=> [2.0] feat: harness: api to process fixtures

harness/src/sysvar.rs
as-configured an epoch is 432k slots, so jumping more than a couple epochs takes several seconds of runtime because `warp_to_slot` must binary search, insert, and truncate `SlotHashes` potentially millions of times. since `SlotHashes` can only contain 512 entries, we can reconstruct it from scratch ~instantly
=> reconstruct slot hashes for long warps

harness/src/sysvar.rs
stake history is segmented by epoch rather than slot. this works because by default both are 0, but isnt correct
=> init stake history with epoch

harness/src/fuzz/firedancer.rs, harness/src/lib.rs, harness/src/sysvar.rs
This PR reworks the way Mollusk creates a sysvar cache for instruction processing.
After this change, the harness will create a new sysvar cache based first on the provided accounts and then on the default values contained in the `Sysvars` object.
This allows fuzz fixtures to provide invalid sysvar account data and see the proper errors in their program's execution as a result.
cc @2501babe
=> harness: rework sysvar caching

fuzz/fixture/proto/invoke.proto, fuzz/fixture/src/effects.rs, harness/src/fuzz/firedancer.rs, harness/src/fuzz/mollusk.rs, harness/src/lib.rs, harness/src/result.rs, harness/tests/fd_test_vectors.rs
using this for minimum delegation tests with normal mollusk, i didnt modify any of the fuzz types since im not sure what support is needed for those
=> add support for return data

harness/src/lib.rs, harness/src/result.rs, harness/tests/dump_fixture.rs, harness/tests/instruction_chain.rs, scripts/prepublish.sh
Reimplementation of #73 from [this suggestion](https://github.com/buffalojoec/mollusk/pull/73#pullrequestreview-2546863518) from @febo.
---
This change adjusts the internals of the instruction chain API to support generation of fuzzing fixtures.
Additionally, since checks will play a key role in fixtures down the road, this change also adjusts the API for instruction chains, allowing developers to declare a slice of `Check` for each instruction in the chain separately.
=> support fuzz fixtures in ix chains

harness/src/fuzz/check.rs, harness/src/fuzz/firedancer.rs, harness/src/fuzz/mod.rs, harness/src/fuzz/mollusk.rs, harness/src/lib.rs, harness/src/result.rs, harness/tests/fd_test_vectors.rs, harness/tests/process_fixture.rs
When working with fixtures, it's sometimes necessary to configure Mollusk's program cache before running some set of fixtures.
In the current implementation, functions such as `process_and_validate_fixture` are associated functions, so they vend their own new `Mollusk` instance internally and use that for processing the fixture, giving the developer no opportunity to configure the program cache (or any other configurations).
This change makes these functions _methods_ using `&mut self`, which causes the loaded fixture to update the current `Mollusk` instance's configurations based on the fixture.
A few notes:
* For any developers who do _not_ wish to alter their `Mollusk` instance based on loaded fixtures, the `load_fixture` function will no longer vend a `Mollusk` instance, but the …
=> fuzz: refactor fixture processing harnesses to use `&mut self`

cli/src/main.rs
Fixes
```
warning: this `map_or` can be simplified
--> cli/src/main.rs:97:19
|
97 |         } else if path.extension().map_or(false, |ext| ext == extension) {
|                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
= note: `#[warn(clippy::unnecessary_map_or)]` on by default
help: use is_some_and instead
|
97 -         } else if path.extension().map_or(false, |ext| ext == extension) {
97 +         } else if path.extension().is_some_and(|ext| ext == extension) {
```
=> Fix clippy warning

cli/src/main.rs, cli/src/runner.rs
Cleans up the stdout of a `run-test` command, eliminating verbosity and allowing scripts to key on the final result stdout pattern.
=> CLI: clean up run-test stdout

bencher/src/lib.rs, bencher/src/result.rs
```md
Solana CLI Version: solana-cli 2.2.0 (src:8b11c7d5; feat:3294202862, client:Agave)
| Name | CUs | Delta |
|------|------|-------|
| bench0 | 44 | - new - |
| bench1 | 44 | - new - |
| bench2 | 44 | - new - |
| bench3 | 44 | - new - |
| bench4 | 44 | - new - |
| bench5 | 44 | - new - |
| bench6 | 44 | - new - |
```
=> bencher: add solana cli version to markdown

cli/src/main.rs, cli/src/runner.rs
This was driving me nuts, as it was very confusing to follow. Now, both commands treat the provided binary as the "target", and `run-test` has the additive "ground truth".
=> cli: reorder ground and target parameters

harness/src/lib.rs
I know the the default paths are located at the top of file.rs but when a dev has an issue with `Mollusk::new` It takes them a minute to track the `load_program` func and since the comments for `Mollusk::new` references the "default path" it should be highlighted
=> docs: add default paths to Mollusk::new

Cargo.toml, bencher/Cargo.toml, cli/Cargo.toml, error/Cargo.toml, fuzz/fixture-fd/Cargo.toml, fuzz/fixture/Cargo.toml, fuzz/fs/Cargo.toml, harness/Cargo.toml, keys/Cargo.toml, programs/memo/Cargo.toml, programs/token/Cargo.toml
`LICENSE` file in the root is **Apache-2.0**, however packages are published to the `crates.io` under the **MIT**
use proper license name in the root `Cargo.toml`
=> fix: use correct license name in Cargo.toml

harness/src/lib.rs, harness/src/result.rs, harness/tests/bpf_program.rs
Adds a new account check to assert a resulting account is rent-exempt.
```rust
Check::account(&key)
.rent_exempt() // <--
.build()
```
When the check is provided to `Mollusk::process_and_validate_instruction`, it uses the Rent instance located at `mollusk.sysvars.rent`. However, this check can also be provided to functions like `InstructionResult::run_checks`.
Note that this is a breaking change. It updates `InstructionResult::run_checks` to accept a `CheckContext` trait implementation, which can offer certain methods such as `is_rent_exempt` for use in checks. I felt like it was best to make this breaking and remove any other "run checks" methods, to make it very clear that you will need to provide a way to check rent exemption (and likely other checks in the future) if you don't pass …
=> harness: add rent-exemption account check

Cargo.lock, Makefile, harness/src/lib.rs, harness/src/program.rs, harness/tests/custom_syscall.rs, test-programs/custom-syscall/Cargo.toml, test-programs/custom-syscall/src/lib.rs
This PR adds the ability to register custom syscalls in Mollusk's test environment. This allows developers to define their own custom syscalls, register them with the test environment, then write programs that access these syscalls and test their functionality.
Since program cache entries for Agave's JIT cache require an environment parameter of type `Arc<BuiltinProgram<InvokeContext<'static>>>`, creating an API for developers to register syscalls was slightly convoluted. 
* Add an owned `BuiltinProgram<InvokeContext<'static>>` field to `ProgramStore` directly, which can be updated when new functions are registered. 
* Each time a program is added to the store, instead of calling `create_program_runtime_environment_v1`, create a new loader from the config and function registry of the …
=> Support registering custom syscalls

rust-toolchain.toml
right now there is no way to auto provide `rustup` toolchains and their  associated pieces. to install, remove, update, etc
use `rust-toolchain.toml` and pin channel to `1.86.0`
=> chore: add `rust-toolchain.toml`

Cargo.lock, Makefile, harness/src/epoch_stake.rs, harness/src/lib.rs, harness/tests/custom_syscall.rs, harness/tests/epoch_stake.rs, test-programs/epoch-stake/Cargo.toml, test-programs/epoch-stake/src/lib.rs
Adds support for populating a cache of "epoch stakes", which can be used to serve the `sol_get_epoch_stake` syscall in program tests.
=> feat: epoch stake syscalls

programs/token/src/token2022.rs
Use loader v3 to add token-2022 to align with onchain deployment
=> fix: add token-2022 program with loader v3

harness/src/lib.rs
"the" -> "to" 
david says I got a sharp eye : )
=> fixes typo

harness/src/lib.rs, harness/src/sysvar.rs
Previously, #150 only added these accounts if they did not already exist. However, once you run a single invocation, the accounts are stored and thus never overwritten. Therefore, we should be hydrating accounts like sysvars each time.
For anyone who wishes to opt-out, or force the harness to use their provided accounts for those keys, I've also included a boolean flag.
=> fix: context: hydrate programs & sysvars every time

harness/Cargo.toml, harness/src/lib.rs, harness/src/program.rs
This should help keep heavy dependencies out of the base library, such as `openssl`.
=> harness: put precompile libs behind feature flag
